PREFIX : <https://ukfires.org/probs/ontology/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?Observation
WHERE {
    ?Observation :objectDefinedBy [ :objectName "Crushed stone in BGS" ] .
}
ORDER BY ?Observation
