PREFIX : <https://ukfires.org/probs/ontology/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?WDF
WHERE {
    :ComposedInferredObservation--7af16db03ac2ac2a9a773645b069b7dacffa239f5b98b9887fa4a0323b787ce7
                   prov:wasDerivedFrom ?WDF .
    ?WDF a :DirectObservation .
}
ORDER BY ?WDF
