PREFIX : <https://ukfires.org/probs/ontology/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT DISTINCT ?Observation
WHERE {
    ?Observation :objectInferredDefinedBy [ :objectName "Crushed stone in BGS" ] . # prov:wasDerivedFrom [ :objectDefinedBy [ :objectName "Sandstone in BGS" ] ] .
}
ORDER BY ?Observation
