PREFIX : <https://ukfires.org/probs/ontology/>
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT ?Observation ?Object ?Year ?Bound ?Value
WHERE {
  ?Observation :objectDefinedBy [ :objectName ?Object ] ;
               :hasRegion [ gn:name "United Kingdom" ] ;
               :hasRole :SoldProduction ;
               :hasTimePeriod [ time:year ?Year ] ;
               :bound ?Bound ;
               :measurement ?Value .
  FILTER( ?Object = "Crushed stone" || ?Object = "Sand & Gravel" )
  FILTER( ?Year = "2014"^^xsd:gYear || ?Year = "2018"^^xsd:gYear )
}
ORDER BY ?Object ?Bound ?Year
